### ISSUE TITLE
odbcinst: SQLRemoveDriver failed with Unable to find component name.

### ISSUE THREAD

**Issue by unformatt** [Microsoft/homebrew-mssql-preview#2]
```
brew install mssql-tools
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin16/rbconfig.rb:213: warning: Insecure world writable dir /usr/local/rvm/gems/ruby-2.0.0-p481 in PATH, mode 040777
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> Updated Formulae
yarn

==> Installing mssql-tools from microsoft/mssql-preview
==> Installing dependencies for microsoft/mssql-preview/mssql-tools: msodbcsql
==> Installing microsoft/mssql-preview/mssql-tools dependency: msodbcsql
==> Downloading http://download.microsoft.com/download/4/9/5/495639C0-79E4-45A7-B65A-B264071C3D9A/msodbcsql-13.1.5.0.tar.gz
Already downloaded: /Users/matt/Library/Caches/Homebrew/msodbcsql-13.1.5.0.tar.gz
The license terms for this product can be downloaded from
https://aka.ms/odbc131eula and found in
/usr/local/share/doc/msodbcsql/LICENSE.txt . By entering 'YES',
you indicate that you accept the license terms.

Do you accept the license terms? (Enter YES or NO)
YES
==> odbcinst -u -d -n "ODBC Driver 13 for SQL Server"
Last 15 lines from /Users/matt/Library/Logs/Homebrew/msodbcsql/01.odbcinst:
2017-04-28 14:34:34 -0400

odbcinst -u -d -n "ODBC Driver 13 for SQL Server"

odbcinst: SQLRemoveDriver failed with Unable to find component name.

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/microsoft/homebrew-mssql-preview/issues
```

**Comment by meet-bhagdev** [comment]
This is most likely an issue with the unixodbc installation. Our guess is odbcinst.ini is not writable.
Can you run the following and tell us what the output is:
```
$ odbcinst -j
$ ls -l /usr/local/Cellar/unixodbc/2.3.4/etc/odbcinst.ini
```

**Comment by unformatt** [comment]
What will it try to write to /usr/local/etc/odbcinst.ini?

```
odbcinst -j
unixODBC 2.3.4
DRIVERS............: /usr/local/Cellar/unixodbc/2.3.4/etc//usr/local/etc/odbcinst.ini
SYSTEM DATA SOURCES: /usr/local/Cellar/unixodbc/2.3.4/etc/odbc.ini
FILE DATA SOURCES..: /usr/local/Cellar/unixodbc/2.3.4/etc/ODBCDataSources
USER DATA SOURCES..: /usr/local/etc/odbc.ini
SQLULEN Size.......: 8
SQLLEN Size........: 8
SQLSETPOSIROW Size.: 8
```

**Comment by unformatt** [comment]
I've love to get this working on Mac for testing. I've created a BCP wrapper for use with Django. I've tested on Linux and Windows but also need to test on Mac: https://github.com/ExoticObjects/django-sql-server-bcp/

**Comment by meet-bhagdev** [comment]
@unformatt I will work with you to make sure we can get this done 👍 

It will write the following to odbcinst.ini:
```
[ODBC Driver 13 for SQL Server]
Description=Microsoft ODBC Driver 13 for SQL Server
Driver=/usr/local/lib/libmsodbcsql.13.dylib
UsageCount=1
```

What is the output of:  
```
ls -l /usr/local/Cellar/unixodbc/2.3.4/etc/odbcinst.ini
````
Also your odbcinst.ini path seems to be corrupted:
```
DRIVERS............: /usr/local/Cellar/unixodbc/2.3.4/etc//usr/local/etc/odbcinst.ini
```

It has two // in between etc and usr. How did you install unixODBC

**Comment by unformatt** [comment]
```
>>> ls -l /usr/local/Cellar/unixodbc/2.3.4/etc/odbcinst.ini
-rw-r--r--  1 matt  admin     0B Aug 31  2015 /usr/local/Cellar/unixodbc/2.3.4/etc/odbcinst.ini
```

I installed unixodbc a long time ago but I think I did it this way:

```
brew install unixodbc --universal
brew link unixodbc
```

**Comment by meet-bhagdev** [comment]
We are not able to install unixodbc the way you did. The current version of unixodbc doesn’t have --universal option and it doesn’t even require linking.

Can you try this?
```
brew remove unixodbc 
brew cleanup -s
#verify unixodbc was uninstalled by calling odbcinst
brew doctor #should say 'Your system is ready to brew'
brew install msodbcsql mssql-tools #this will install all the dependencies (including unixodbc)

```

**Comment by unformatt** [comment]
Still getting that SQLRemoveDriver error:

```bash
>>> brew uninstall --force --ignore-dependencies unixodbc
>>> brew cleanup -s
>>> odbcinst
zsh: command not found: odbcinst
>>> brew install msodbcsql mssql-tools
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin16/rbconfig.rb:213: warning: Insecure world writable dir /usr/local/rvm/gems/ruby-2.0.0-p481 in PATH, mode 040777
==> Installing msodbcsql from microsoft/mssql-preview
==> Installing dependencies for microsoft/mssql-preview/msodbcsql: unixodbc
==> Installing microsoft/mssql-preview/msodbcsql dependency: unixodbc
==> Downloading https://homebrew.bintray.com/bottles/unixodbc-2.3.4.sierra.bottle.1.tar.gz
######################################################################## 100.0%
==> Pouring unixodbc-2.3.4.sierra.bottle.1.tar.gz
🍺  /usr/local/Cellar/unixodbc/2.3.4: 43 files, 2.0MB
==> Installing microsoft/mssql-preview/msodbcsql
==> Downloading http://download.microsoft.com/download/4/9/5/495639C0-79E4-45A7-B65A-B264071C3D9A/msodbcsql-13.1.5.0.tar.gz
######################################################################## 100.0%
The license terms for this product can be downloaded from
https://aka.ms/odbc131eula and found in
/usr/local/share/doc/msodbcsql/LICENSE.txt . By entering 'YES',
you indicate that you accept the license terms.

Do you accept the license terms? (Enter YES or NO)
YES
==> odbcinst -u -d -n "ODBC Driver 13 for SQL Server"
Last 15 lines from /Users/matt/Library/Logs/Homebrew/msodbcsql/01.odbcinst:
2017-05-04 11:31:30 -0400

odbcinst -u -d -n "ODBC Driver 13 for SQL Server"

odbcinst: SQLRemoveDriver failed with Unable to find component name.

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/microsoft/homebrew-mssql-preview/issues
```

**Comment by unformatt** [comment]
From what I understand, the installer is trying to remove "ODBC Driver 13 for SQL Server" incase it already exists but doesn't handle the case that it doesn't exist.

```
system "odbcinst -u -d -n \"ODBC Driver 13 for SQL Server\""  # <--- should be conditional or make sure it doesn't exit with error code that prevents installer from continuing
system "odbcinst -i -d -f ./odbcinst.ini"
```

Appending `|| true` might work:
```|| true
system "odbcinst -u -d -n \"ODBC Driver 13 for SQL Server\"" || true
```

**Comment by unformatt** [comment]
If I remove the uninstall command from `/msodbcsql.rb`, still fails when it tries to install the driver:

```bash
...
==> odbcinst -i -d -f ./odbcinst.ini
Last 15 lines from /Users/matt/Library/Logs/Homebrew/msodbcsql/02.odbcinst.ini:
2017-05-04 11:50:20 -0400

odbcinst -i -d -f ./odbcinst.ini

odbcinst: SQLInstallDriverEx failed with Unable to find component name.

Do not report this issue to Homebrew/brew or Homebrew/core!
```

**Comment by mateusz-kmiecik** [comment]
Hi Matt,

odbcinst uninstall command should work just fine even if the driver is not present in odbcinst.ini. If that’s the case you should get the following message:
“ODBC Driver 13 for SQL Server has been deleted (if it existed at all) because its usage count became zero.”

As you can see from your experiments, even the install command fails, which makes me think that your unixodbc or brew installation is somehow corrupted.
Can you please run ‘brew doctor’ to identify any issues with your installation?

Best regards,
Mat

**Comment by unformatt** [comment]
brew doctor output here:  https://gist.github.com/unformatt/7172506911e30f54089a15374ed11344

**Comment by unformatt** [comment]
I ran brew install with `--verbose --debug` and here's the output:

```bash
brew install mssql-tools --verbose --debug
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin16/rbconfig.rb:213: warning: Insecure world writable dir /usr/local/rvm/gems/ruby-1.9.3-p194/bin in PATH, mode 040777
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/microsoft/homebrew-mssql-preview/Formula/mssql-tools.rb
==> Installing mssql-tools from microsoft/mssql-preview
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/unixodbc.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/openssl.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/makedepend.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/pkg-config.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/microsoft/homebrew-mssql-preview/Formula/msodbcsql.rb
==> Installing dependencies for microsoft/mssql-preview/mssql-tools: msodbcsql
==> Installing microsoft/mssql-preview/mssql-tools dependency: msodbcsql
/usr/local/Homebrew/Library/Homebrew/build.rb (Formulary::FromPathLoader): loading /usr/local/Homebrew/Library/Taps/microsoft/homebrew-mssql-preview/Formula/msodbcsql.rb
/usr/local/Homebrew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/unixodbc.rb
/usr/local/Homebrew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/openssl.rb
/usr/local/Homebrew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/makedepend.rb
/usr/local/Homebrew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/pkg-config.rb
==> Downloading http://download.microsoft.com/download/4/9/5/495639C0-79E4-45A7-B65A-B264071C3D9A/msodbcsql-13.1.5.0.tar.gz
Already downloaded: /Users/matt/Library/Caches/Homebrew/msodbcsql-13.1.5.0.tar.gz
==> Verifying msodbcsql-13.1.5.0.tar.gz checksum
tar xzf /Users/matt/Library/Caches/Homebrew/msodbcsql-13.1.5.0.tar.gz
The license terms for this product can be downloaded from
https://aka.ms/odbc131eula and found in
/usr/local/share/doc/msodbcsql/LICENSE.txt . By entering 'YES',
you indicate that you accept the license terms.

Do you accept the license terms? (Enter YES or NO)
YES
==> odbcinst -u -d -n "ODBC Driver 13 for SQL Server"
odbcinst: SQLRemoveDriver failed with Unable to find component name.
/usr/local/Homebrew/Library/Homebrew/debrew.rb:11:in `raise'
BuildError: Failed executing: odbcinst -u -d -n "ODBC Driver 13 for SQL Server"
1. raise
2. ignore
3. backtrace
4. irb
5. shell
Choose an action: 2
==> odbcinst -i -d -f ./odbcinst.ini
odbcinst: SQLInstallDriverEx failed with Unable to find component name.
/usr/local/Homebrew/Library/Homebrew/debrew.rb:11:in `raise'
BuildError: Failed executing: odbcinst -i -d -f ./odbcinst.ini
1. raise
2. ignore
3. backtrace
4. irb
5. shell
Choose an action: 2
==> Cleaning
==> Finishing up
ln -s ../Cellar/msodbcsql/13.1.5.0/include/msodbcsql.h msodbcsql.h
ln -s ../../Cellar/msodbcsql/13.1.5.0/share/doc/msodbcsql msodbcsql
ln -s ../Cellar/msodbcsql/13.1.5.0/share/msodbcsql msodbcsql
ln -s ../Cellar/msodbcsql/13.1.5.0/lib/libmsodbcsql.13.dylib libmsodbcsql.13.dylib
Changing dylib ID of /usr/local/Cellar/msodbcsql/13.1.5.0/lib/libmsodbcsql.13.dylib
  from /Users/bamboo/bamboo-agent-home/xml-data/build-dir/LO-MBT-BR/Dev.build/retail/Darwin/amd64/Sql/Ntdbms/sqlncli/libmsodbcsql.dylib
    to /usr/local/opt/msodbcsql/lib/libmsodbcsql.dylib
==> Caveats
If you installed this formula with the registration option (default), you'll
need to manually remove [ODBC Driver 13 for SQL Server] section from
odbcinst.ini after the formula is uninstalled. This can be done by executing
the following command:
    odbcinst -u -d -n "ODBC Driver 13 for SQL Server"
==> Summary
🍺  /usr/local/Cellar/msodbcsql/13.1.5.0: 8 files, 2.5MB, built in 16 seconds
==> Installing microsoft/mssql-preview/mssql-tools
/usr/local/Homebrew/Library/Homebrew/build.rb (Formulary::FromPathLoader): loading /usr/local/Homebrew/Library/Taps/microsoft/homebrew-mssql-preview/Formula/mssql-tools.rb
/usr/local/Homebrew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/unixodbc.rb
/usr/local/Homebrew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/openssl.rb
/usr/local/Homebrew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/microsoft/homebrew-mssql-preview/Formula/msodbcsql.rb
/usr/local/Homebrew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/makedepend.rb
/usr/local/Homebrew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/pkg-config.rb
==> Downloading https://go.microsoft.com/fwlink/?linkid=845605
==> Downloading from http://download.microsoft.com/download/F/D/1/FD16AA69-F27D-440E-A15A-6C521A1972E6/mssql-tools-14.0.5.0.tar.gz
/usr/bin/curl --remote-time --location --user-agent Homebrew/1.2.0 (Macintosh; Intel Mac OS X 10.12.1) curl/7.49.1 --fail http://download.microsoft.com/download/F/D/1/FD16AA69-F27D-440E-A15A-6C521A1972E6/mssql-tools-14.0.5.0.tar.gz -C 0 -o /Users/matt/Library/Caches/Homebrew/mssql-tools-14.0.5.0.incomplete
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  350k  100  350k    0     0  1339k      0 --:--:-- --:--:-- --:--:-- 1343k
==> Verifying mssql-tools-14.0.5.0 checksum
tar xzf /Users/matt/Library/Caches/Homebrew/mssql-tools-14.0.5.0
The license terms for this product can be downloaded from
http://go.microsoft.com/fwlink/?LinkId=746949 and found in
/usr/local/share/doc/mssql-tools/LICENSE.txt . By entering 'YES',
you indicate that you accept the license terms.

Do you accept the license terms? (Enter YES or NO)
YES
==> Cleaning
Fixing /usr/local/Cellar/mssql-tools/14.0.5.0/bin/bcp permissions from 444 to 555
Fixing /usr/local/Cellar/mssql-tools/14.0.5.0/bin/sqlcmd permissions from 444 to 555
==> Finishing up
ln -s ../Cellar/mssql-tools/14.0.5.0/bin/bcp bcp
ln -s ../Cellar/mssql-tools/14.0.5.0/bin/sqlcmd sqlcmd
ln -s ../Cellar/mssql-tools/14.0.5.0/share/resources resources
==> Summary
🍺  /usr/local/Cellar/mssql-tools/14.0.5.0: 11 files, 1.1MB, built in 9 seconds
```

Ran bcp to see what it would say:

```
bcp
Unable to locate driver dynamic library. BCP cannot continue.
```

**Comment by unformatt** [comment]
So linking of msodbcsql files (from msodbcsql-13.1.5.0.tar.gz) appears to be failing even though there is no error shown. This might come back to what Meet brought up, which is that my
unixodbx DRIVERS path shows as `/usr/local/Cellar/unixodbc/2.3.4/etc//usr/local/etc/odbcinst.ini`

**Comment by unformatt** [comment]
Problem solved!

Took a look at unixodbc source to find where it gets the `DRIVERS` path and found that it gets `odbcinst.ini` path by concatenating `odbcinst_system_file_path` and `odbcinst_system_file_name`.

I had an env var in my shell profile that was overriding `odbcinst_system_file_name` like this

```
export ODBCINSTINI=/usr/local/etc/odbcinst.ini
```

Which then caused the weird path of `/usr/local/Cellar/unixodbc/2.3.4/etc//usr/local/etc/odbcinst.ini`

I removed the `ODBCINSTINI` env var and installation of **mssql-tools** succeeded. Thanks for the help!

**Comment by mateusz-kmiecik** [comment]
I’m glad you were able to solve the problem! That was a tricky one ☺

Cheers,
Mat

**Comment by unformatt** [comment]
@meet-bhagdev Now that this is working, do you know why I can BCP to my database from macOS (using mssql tools for macOS) but if I try to BCP to same database with same user/pass from Windows, I get `Connection is not enabled for BCP` ?

**Comment by meet-bhagdev** [comment]
@unformatt FYI we have now RTW'd the driver and tools: https://github.com/Microsoft/homebrew-mssql-release

@abhisheksinha89 @tara-raj can you take a look at the BCP issue?
